[CATYA]
#Screen Title
Title = CATYA

#App Icon
app_icon = /catya.png

#Toolbar icons
toolbar_start    = /start.png
toolbar_stop     = /stop.png
toolbar_pause	 = /pause.png

#Tooltip
tooltip_start = Start
tooltip_stop = Stop
tooltip_pause = Pause

#Number of table rows
#table_rows = 1048576
table_rows = 100000

#Mailer Table info
table_columns = Item, 50, Test Cases, 150, Steps, 500, Expected Result, 100, Actual Result, 100, Status, 100

#Messages
message_confirmation = Are you sure you want to close the window?